package org.example.logica;

public enum Recorridos {
    CONCEPCION,CHILLAN,LOS_ANGELES,CHILLANCONCEPCION,CHILLANLOS_ANGELES,CONCEPCIONLOS_ANGELES,CONCEPCIONCHILLAN,LOS_ANGELESCONCEPCION,LOS_ANGELESCHILLAN;
}
